### ISSUE TITLE
Since last update is not working.

### ISSUE THREAD

**Issue by rickytin** [nosmokingbandit/watcher#106]
I delete watcher and downloaded again with Git and enter all information (Sabnzbd, 7 provider) and I do a test adding a movie that I know my providers have but it docent find it.
Help what can be the problem.

**Comment by alazare619** [comment]
This has happend to me as well.. Just did a git pull to update the source and same thing...indexers are there everything is good but no results.

**Comment by alazare619** [comment]
currently on git checkout 5829dc1505f1963935684a8e1c994c9b4664b677
everything is working ok again.

**Comment by nosmokingbandit** [comment]
Commit https://github.com/nosmokingbandit/watcher/commit/1cfde6b719779dae7fbef9360d6cd27fa1d1eb4f should have fixed this. 

In order to make things work with NZBHyrda's forwarding I had to add a separate check in the search process, which accidentally cut out everything *except* nzbhydra results. Some days I just can't win.

Anyway, report back so I can close this if you are fixed up.

**Comment by alazare619** [comment]
@nosmokingbandit  after git fetch to 1cfde6b everything seems to be working now.
