### ISSUE TITLE
Watcher snatches '1080 web-dl' release instead of '1080p bluray'

### ISSUE THREAD

**Issue by MartinAyla** [nosmokingbandit/watcher#108]
When I search for a certain movie, I can see 1080p web-dl releases and 1080p bluray releases.

Watcher has snatched the web-dl but I of course want it to prioritize bluray releases.

Any ideas how I can fix this?

Thanks

**Comment by Flippage** [comment]
Required words: webdl, web-dl, bluray, blu-ray
Preferred words: bluray, blu-ray

This SHOULD be the way it works. Preffered words should give a higher score than non-preferred words.

I don't know if this is how the dev has built it, but you can try it and let us all know :)

**Comment by MartinAyla** [comment]
Thanks, I will try that.

It seemed to "just work" in Couchpotato, meaning that it knew that bluray was preferred over web-dl, without me having to set required/preferred words.

**Comment by nosmokingbandit** [comment]
Preferred words add 10 points to the score, so the more preferred words the better, of course.

It sorts by resolution priority + 100 points

Preferred words + 10 points each

Then it matches the title. Anything less than a 60% match is ignored, and anything higher adds points accordingly.

If adding `blu-ray` to `preferred words` gets the results you want please close this issue.

If not we'll chat more about refining the algorithm. That was one of the hardest parts of the dev process since there is no *right* way to score movies. I just kind of tweak all of the numbers until I get what you want. Then when I don't get what I want you go back in and tweak a little more.

**Comment by MartinAyla** [comment]
Thanks for the replies, I can see that it's not that simple to prefer bluray over web-dl releases.

I already have "BluRay" under preferred words, I see.

**Comment by nosmokingbandit** [comment]
Email me at watchernzb@gmail.com with more specific details of what particular release you are looking at and your quality settings (a screenshot of the slide-up panel would be great).

I just added BDRip to a movie's preferred words since bd-rip was already the top result, and after searching again it pushed the BDRip release to the op of the list.

**Comment by nosmokingbandit** [comment]
This ended up being a bug that had already been fixed, but we needed to change search settings to trigger a re-search prompt. This should not happen again, but I promise nothing.
