### ISSUE TITLE
Watcher is grabbing "soundbites", "trailers" and "behind the scenes"

### ISSUE THREAD

**Issue by MartinAyla** [nosmokingbandit/watcher#111]
I'm seeing this for a lot of movies, the latest jedi movie ;) for example.

This never happened with Couchpotato, so I'm not sure what needs to be done to avoid these?

Btw. thanks a lot for working on watcher, I really like it!

**Comment by nosmokingbandit** [comment]
Watcher searches indexers via the imdb id number, so if your indexer is tagging things incorrectly and the title still matches well enough it is rather difficult to filter it out.

I'll take a look at the latest space battles release and see if I can see what the deal is.

**Comment by nosmokingbandit** [comment]
I went Rogue for One minute and I this should fix you up. I'm still not 100% sure how it was storing the wrong value, because the part I changed doesn't exactly affect how the value is stored, just when it is stored.

Commit https://github.com/nosmokingbandit/watcher/commit/a5dfac38e59782a2e40f1b41b90648fcb817892a gave me the desired results. Or lack thereof.

There are two stages to any kind of software development:
1) It doesn't work and I don't know why.
2) It works and I don't know why.
