### ISSUE TITLE
[Enhancement] Nzbget Failed Download Handling

### ISSUE THREAD

**Issue by alazare619** [nosmokingbandit/watcher#127]
I would like to see failed download handling support added for nzbget and sabnzbd could probably use CP as a refrence for this.

**Comment by alazare619** [comment]
I Should clarify this. I meant without the need for postprocessing script. Similiar to how sonarr already implements this and CP was.

**Comment by WilliamJBrown** [comment]
I personally like the script better. Sadly sonarr is based of mono which has issues in sending files across a network and causes sonarr to freeze for minutes at a time because of it. I can never access sonarr whilst it is downloading and transferring files. Scripts are much more basic and nothing can go wrong because of it :) I use video sort for all my tv shows too.

**Comment by nosmokingbandit** [comment]
Yeah, this is not going to happen. The scripts are rather easy to use. Why the aversion to the post-scripts?
