### ISSUE TITLE
requests not getting correct quality 

### ISSUE THREAD

**Issue by soupy14** [nosmokingbandit/watcher#13]
I added a movie it was quality for searching 720p but it started to download a ts 720p, I added ts to my filter for ignored but it keeps saying its snatched now. Anyway to un snatch? Even deleting and re adding still shows snatched.
Also might not be a bad idea to have a restore default settings button.

as per our Reddit conversation I posted it here

**Comment by Firemad03** [comment]
I want to add that I found also that if you put some keywords to required etc. in the settings and you add a movie and after that that you change the required word for example in the setting it doesn't update the movies list. I need to manually edit each movies to add the new keyword.

I expected a global change to all the movies listed.

**Comment by nosmokingbandit** [comment]
If you change the settings in Settings>Quality it doesn't change globally because every movie can have its own completely unique set of quality criteria. If you change the option on that movie itself it works as intended. 

I intend to eventually have the ability to apply changes globally at the user's discretion, but that will take some time.
