### ISSUE TITLE
Quality settings page for a movie broken

### ISSUE THREAD

**Issue by Crowley007** [nosmokingbandit/watcher#143]
Currently the quality settings page does not show all the settings and can't be scrolled:

![capture](https://cloud.githubusercontent.com/assets/23026322/21890741/ca1a1a86-d8d7-11e6-953c-d13489452483.JPG)

**Comment by Alamei** [comment]
I can confirm this behavior, tested across Firefox, Chrome and Edge. The problem is the default 40px left padding most browsers add to <ul> elements. For an app like this, you most likely only want to have explicit padding on lists, so I would recommend just resetting them all to zero and adding padding back anywhere it's actually desired.

For any users with Stylish installed, you can apply a quick fix by creating a script for your watcher domain and adding the following single line:
`ul {padding-left: 0;}`

**Comment by vertigo235** [comment]
When adding a movie it looks like the required words and ignored words section is blocked out too...

![image](https://cloud.githubusercontent.com/assets/1238461/21900898/9e1114c6-d8c3-11e6-81f5-ce87bb17722e.png)

**Comment by Crowley007** [comment]
Seems to be working again.

**Comment by Alamei** [comment]
It looks like the CSS is fixed, but the CSS links lack versioning strings. That means some users will continue to see the buggy CSS until they perform a hard refresh in their browser. I would recommend adding versioning strings to the CSS files that get incremented when you update them to ensure that cached versions aren't served.

**Comment by nosmokingbandit** [comment]
I've often thought about adding version strings to the css url, but I always got caught up in other things instead and never did it.
