### ISSUE TITLE
"Error Checking for Updates Current local hash not in git history."

### ISSUE THREAD

**Issue by CKyle22** [nosmokingbandit/watcher#163]
I receive that when opening Watcher. I cloned from git on Windows per the instructions. Current version hash in the settings is 2fbd6f9

**Comment by nosmokingbandit** [comment]
What happens when you open a command line and enter simply `git`?

**Comment by CKyle22** [comment]
Nothing, although when you install git on Windows, it comes with it's own command prompt...

**Comment by nosmokingbandit** [comment]
Watcher needs to be able to execute git, so if the git binary isn't in your PATH it will throw an error.

The PATH in windows is basically a directory that points it toward programs. So instead of typing `C:\\Path\To\Git.exe` you have the same effect with `git`.

Its easy to remedy, just follow this post.

http://stackoverflow.com/questions/26620312/installing-git-in-path-with-github-client-for-windows/34767523#34767523
