### ISSUE TITLE
timeout error in sabnzbd.py during post processing.

### ISSUE THREAD

**Issue by tinstep** [nosmokingbandit/watcher#185]
Hi 
During postprocessing, there is an error when the sabnzbd.py is called.

Here is the output from Sabnzbd:
`Traceback (most recent call last):
  File "/home/cam/.apps/autoProcessTV/sabnzbd.py", line 67, in <module>
    request = urllib2.Request(url, post_data, headers={'User-Agent': 'Mozilla/5.0'}, timeout=600)
TypeError: __init__() got an unexpected keyword argument 'timeout'`

IM not seeing anything in the watcher log?

**Comment by Alamei** [comment]
It looks like you're using an old version of the post-process script, since that bug was patched out in this commit a few days ago: c554b5fa1d2b199a398e5bf99019c5874a5ec479.

Unfortunately, the post-process scripts can't currently be auto-updated, since they reside in other directories. You'll have to go through the process of adding your API details to the new version and copying it over to your Sabnzbd folder again.

**Comment by nosmokingbandit** [comment]
I think I've got the post-scripts finalized, so hopefully this doesn't happen again. But yes, this was a dumb typo on my part.
