### ISSUE TITLE
releases not listed on predb

### ISSUE THREAD

**Issue by t4nkw4rt** [nosmokingbandit/watcher#188]
#### What happened?
added a recently released movie, listed on dog.
ran the search, even adjusted the time for auto search.
watcher first checked predb and then did not do anything.

#### What was supposed to happen?
watcher grabs the movie and sends to downloader.

#### How can I reproduce this?
happens IMHO to all movies not listed on predb.

nosmokingbandit, check email for nzb name.

**Comment by Elfman72** [comment]
I understand why this is done (to avoid bogus releases and fakes with automation) and I am okay with it.  I just wish there was a notice either in the log or in the UI that stated something about it. "Release not found in predb. Cancelling Indexer search."  Or maybe even have an option to mark those releases a different color so that you can download them manually.  These non-predb releases would never automatically be downloaded but would still allow the user to manually grab them.  Then once they are found in predb, the color would be removed and eligible for automatic download.

**Comment by t4nkw4rt** [comment]
yeah, have them in different color in the UI for manual download would be great.

**Comment by soundjester** [comment]
@Elfman72 [I saw your reddit thread on this.](https://www.reddit.com/r/watcher/comments/5ol201/searching_and_predb_dependencies/)

Having some way to bypass PreDB checks would probably be a good idea (provided that it is explicit and the user understands the risks) and a user-facing indication of what is happening behind the scenes would nip some "movie isn't found/won't download" bug reports before they get written.

**Comment by nosmokingbandit** [comment]
I'm going to change the manual search to bypass the predb check. That way you'll be able to see bad results immediately and change them if necessary.
