### ISSUE TITLE
Feature Request - Prepoluted List of Newznab Indexers

### ISSUE THREAD

**Issue by averagecdn** [nosmokingbandit/watcher#195]
In some clients they provide a drop down where you can select your search site. It would be great if something like that could exist in Watcher. Its painstaking to go through all my sites and copy and paste all the API Urls and there api key.

**Comment by nosmokingbandit** [comment]
You have to copy the api key anyway. Copying the url takes all of 3 more seconds?

**Comment by Technifocal** [comment]
@nosmokingbandit playing devil's advocate, I managed to get my dognzb account suspended for 24 hours for using dognzb.cr, rather than api.dognzb.cr, which this issue would have resolved as I would have never typed the incorrect URL.

On the other hand, I didn't read the instructions, so, I can only blame myself.
