### ISSUE TITLE
Feature Request: PlexRequests

### ISSUE THREAD

**Issue by Firemad03** [nosmokingbandit/watcher#33]
Hi,

I suggest to make it compatible with Plex Requests. http://plexrequests.8bits.ca/ 

Plex Requests is compatible with CouchPotato.

Thanks

**Comment by ywLBhGk2noZLbY7** [comment]
Surely this is something that the developer of Plex Requests should implement, rather than Watcher emulating the CouchPotato API. Watcher has an (undocumented) API for this, which [looking at the file](https://github.com/nosmokingbandit/watcher/blob/master/core/api.py) is roughly:

`/api?apikey=${APIKEY}&mode=addmovie&imdbid=tt1254207`

**Comment by nosmokingbandit** [comment]
The fellow who handles plexrequests posted on Reddit a few days ago. We plan on working together on it when he has the time. I have a basic api in place that is easy to manipulate, so I believe we should have no trouble doing this.

But, to echo ywLBhGk2noZLbY7, this is something Plexrequests would need to do.

I'm going to close this, not because it isn't a valid issue, but because it isn't *my* issue ;)
