### ISSUE TITLE
Feature Request: Import an existing folder that contain movies

### ISSUE THREAD

**Issue by Firemad03** [nosmokingbandit/watcher#40]
Hi,

Import an existing folder that contain movies. 

CouchPotato have this feature and I like it because if I want to update my movies collection to have a better quality that take less space I will be able to do it with Watcher ;)

Thanks

**Comment by judhat2** [comment]
+1 for this.  It would be good to see if I already have a movie downloaded or not.

**Comment by nosmokingbandit** [comment]
I'm not sure how I feel about this. I don't want to expand this out into library management territory. I really just want to focus on grabbing and post-processing quickly and efficiently.

I'll think about it, but either way it won't happen soon.

**Comment by Firemad03** [comment]
> I'm not sure how I feel about this. I don't want to expand this out into library management territory. I really just want to focus on grabbing and post-processing quickly and efficiently.

Well I think the minimum goal is to check the directory and list all the movies in it with the quality. Sometimes the Movie is at 720p or another quality but I want Watcher to check it out and find a better quality in the future and for example 1080p or later 4k if I want to. 

Sometime in usenet the quality isn't there yet because the blueray isn't available yet or the movie is too old and you have a dvd edition and bang one day you got the blueray ;)

I agree that we don't need the library management with all the feature but if we focus to improve it by grapping a better quality it will be a nice feature for Watcher. 

Right now Watcher is already doing it for new movie to find the best quality but it will be nice to have it for an old collection. That's how I saw the feature.

But your right it isn't a short term goal because you have other stuff to do ;) I saw it as a long term goal or want you have the time to it.

**Comment by nosmokingbandit** [comment]
The thing is, scoring already processed releases isn't entirely accurate.
Say I had a preferred release group that I put in Preferred Words. That
will score 10 points higher than a release without that word. But if I'm
looking at scoring simply 'Name of movie.mkv' you may just end up
downloading a new copy that is the exact same thing simply because the new
release title has the group name in it.

The only workaround I can figure is to require that re-grabs score at least
100 points higher than the existing release, since resolution priority adds
100 points.

I'll think about it a bit and see if I can come up with something good.

**Comment by nosmokingbandit** [comment]
Hey I think I came up with something good.

Update to commit https://github.com/nosmokingbandit/watcher/commit/a50899b78963ea77ad8655ebec1d1712d5800e8b and take a look.

I'm certain things will go wrong but I've tried to break this in every way I could and it works for me.

For anyone interested:
Scoring is the problem. Importing a movie is easy, but how do I know what score to assign to it so Watcher doesn't automatically grab the top result on the next search schedule, even if the new result is worse?

I need to make a 'fake' search result in order to generate a score, and this 'fake' result will need to have all of the information possible. I can get the title, and after that the imdb id and such information from the file name, but that only gets me half way there.

So I got hachoir-metadata working and use it to figure out the audio/video codecs and resolution. Then, when adding the movie to the library it creates a name for the fake result by concatenating the movie title, year, resolution, audio codec, video codec, and release group into something like `Super.Cool.Movie.2017.720P.DTS` depending on what info is available.

Since 90% of scoring is done off of the release title, I can now use this to add points for preferred words and get a search result that should be - in theory - within ~20 points of the 'real' score. This is great because you can set Watcher to grab only movies that core X points higher, so you won't immediately overwrite your library.
