### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by kaboomwarrior** [nosmokingbandit/watcher#48]
Add proxy support. This is pretty straightforward as urllib2 has built support for this. Now can be used by setting system wide HTTP_PROXY and HTTPS_PROXY environment variables, however would be simpler to add this to config and UI.

**Comment by tidusjar** [comment]
Looks like this can be done in the `config.cfg` file, there is a `PROXY` section.

Set `behindproxy` to true and `webroot` to your base url

**Comment by kaboomwarrior** [comment]
Yes, but this is about connection proxy (connection from within watcher proxied via HTTP/HTTPS proxy), not reverse proxy.

**Comment by nosmokingbandit** [comment]
This is actually a little more complicated that just assigned the envars. You can't have local connections go through a proxy or all of your nzbhydra connections will fail. So there have to be bypass conditions and methods based on a url whitelist.

Urllib2 has no *easy* way of using a socks proxy, so that had to be added separately with its own bypass method (although my bypass method just switches to the default socket and urllib2 opener for a single request, so it handles both).

This wasn't a huge priority so I didn't start it until yesterday, and didn't finish it until today because it ended up being a little more complicated than it seems on the surface.

This feature is added in commit https://github.com/nosmokingbandit/watcher/commit/a40f80ef20d8205f1394ff31496d270a98163cf6

I tested http, https, and socks5 as much as I could. Socks4 functions almost identically to Socks5, so that should be fine as well. This only tunnels connections to search providers. I don't think any countries have TMDB.org blocks (maybe China does?), and other innocuous connections shouldn't need to be tunneled.

I use a VPN rather than proxy, so I don't know your exact requirements. Let me know if you run into trouble. Until then I'm going to close this.
