### ISSUE TITLE
Don't force HTTP when served via HTTPS

### ISSUE THREAD

**Issue by mescon** [nosmokingbandit/watcher#53]
Hello!
I have nginx setup acting as a reverse proxy with SSL support.

When visiting https://mydomain.com/watcher it tries to redirect to http://mydomain.com/watcher/status (note the missing https).

When used inside of Muximux for instance, this renders the page blank as all the contents of the frame are served as HTTPS except for Watcher - and is therefore blocked.

You could just serve with //mydomain.com/watcher/status and the browser itself will prepend http or https depending on how it's accessed.

**Comment by duckduckquack** [comment]
Sounds like a problem with Muximux; Watcher doesn't exhibit this behavior in a standard nginx reverse proxy...

**Comment by Crowley007** [comment]
Sounds similar to my problem here: https://github.com/nosmokingbandit/watcher/issues/6

And I'm using idashboard, it works like muximux so I doubt the problem is there. Every other app works fine.

**Comment by nosmokingbandit** [comment]
The only thing that happens when vising the watcher index page ie `https://localhost:9090/` is a redirect to `/status`. It doesn't coerce anything to a different base url.

I don't have https set up on my server, but I'll try to get it working then report back.

**Comment by jimbo2412** [comment]
Running update ` e0389d9`. Watcher will not load if I attempt to access `https://127.0.0.1:9393/watcher`.

**Comment by mescon** [comment]
If I go to https://mydomain.com/watcher/status/ everything is fine - if i go to https://mydomain.com/watcher it redirects me to http://mydomain.com/watcher/status (without https).

Same thing with the updater - if I click "check for updates now" it tells me there are updates to install, but when i click install it throws ``Mixed Content: The page at 'https://mydomain.com/' was loaded over HTTPS, but requested an insecure resource 'http://mydomain.com/watcher/update/'. This request has been blocked; the content must be served over HTTPS.`` in the console.

I updated to b215881a1bdf47c31e3a730c8e14c07d64db607a - and the issue remains.
The temporary workaround for me is to simply use https://mydomain.com/watcher/status/.

**Comment by duckduckquack** [comment]
@mscon can't you just adjust nginx to only work over https?

`server {`
`    listen 80;`
`    server_name server.domain.com;`
`    return 301 https://$server_name$request_uri;`
`}`

**Comment by Crowley007** [comment]
Hopefully this does not go too much off topic, but I still think this has to do with the same issue I have with reverse proxy when I use anything else than "listen 80" in nginx server config.

Because for me the same thing happens, https://mydomain.com/watcher/status/ works, https://mydomain.com/watcher does not work. 

There is something that watcher does differently when redirecting than every other app with webui I use. There may be ways to work around it, but perhaps it would be worth it to find the  cause.

**Comment by nosmokingbandit** [comment]
After smashing my face into my keyboard for a few minutes I think I'm on to something. I want to test it more tomorrow morning (for alas it is my bedtime).


Long, boring explanation:


I found that going to /settings/X would stay on https, but going to /add_movie or /status would not. This confused me. The only difference is that it is going to a subpage.


Well, in settings/X, it loads the settings template, then executes a method name X that renders the content for that page. It basically executes settings.server() and returns the html the template produces.
That's interesting. If you don't supply a function to execute, cherrypy looks for index.html, and when it can't find that, fires index(). So the only time it switches to http is when executing the index() method in the template.


I test this by renaming index() to balls() (because apparently I have the humor of a pre-teen boy), and go to /watcher/status/balls and it loads up in https just fine.


AHA! I exclaimed, still not entirely sure what to do with this new information.


I recall at one point seeing a cherrypy example where the author used the method name default() instead of index(). I didn't think much of it because cherrypy's docs all use index() and there must surely be a reason for that. But I switched AddMovie.index() to AddMovie.default() and it loaded up from /watcher/addmovie. AHA! I exclaimed, still a little confused, but rolling with the renewed vigor of discovery.


I load up my sites via https://www.ddsnprovier.com/watcher/status. I hover my mouse over Add Movie. Cautious. Careful. I slowly press the mouse button. The room is deathly silent. A single bead of sweat drips from my nose and splashes thunderously on my desk. I close my eyes, afraid that this was all for naught.


*click*


I exhale slowly. It is done. Success or failure, I feel the weight of apprehension lessen as my eyelids begin to part.


https://www.ddsnprovier.com/watcher/addmovie

It shines gloriously from my navigation bar. The beauty is blinding. I hear children laughing, fireworks in the distance. A subtle warmth spreads through my body, pausing at my fingertips and toes.


I'm exhausted. Weary. But revitalized nonetheless. I gather my remaining strength and with haste hammer out this tale, keys clicking furiously. And as the story closes so do my eyes. For alas, it is.... my bedtime.

**Comment by mescon** [comment]
This is the best bughunt ever :)

**Comment by nosmokingbandit** [comment]
I just pushed commit https://github.com/nosmokingbandit/watcher/commit/55c70b2791d85be051b7cecb4d3141208de88a10

In my testing this kept my browser pointed toward https://mysite.com regardless of my use and abuse. I still can't figure out why Cherrypy changes url scheme when using `index` as the method name for page dispatching, but `default` works, so whatever.

The rest was easier once I stopped trying to make CherryPy handle *everything*. Had I started with ajax form submission I wouldn't have had any problems, but I was convinced CherryPy would do something it just isn't capable of in this particular arrangement.

Please report back *ONLY* if this works. I have other bugs to squash, so only affirmative reports will be accepted. *


*really though, let me know either way.

**Comment by jimbo2412** [comment]
Updated to` 55c70b2` nginx is now working for me!
Thanks

**Comment by Crowley007** [comment]
This finally fixed the problem I was having with nginx. Nice!
