### ISSUE TITLE
Not working with NZBHydra

### ISSUE THREAD

**Issue by selotapeb** [nosmokingbandit/watcher#82]
I've just updated to the new Docker image, and for some reason when I use my local NZBHydra server as a provider, searches are showing no results in Watcher. I can see from the logs that it is hitting my server, and results are being returned by NZBHydra, but Watcher doesn't seem to use them:

INFO 2017-01-01 05:35:33,973 core.newznab.search_all: SEARCHING: http://nzbhydraurl:8008/api?apikey=APIKEY&t=movie&imdbid=movieid
INFO 2017-01-01 05:35:39,071 core.sqldb.get_search_results: Retreving Search Results for ttmovieid
INFO 2017-01-01 05:35:39,075 core.sqldb.get_movie_details: Retreving details for ttmovieid.
INFO 2017-01-01 05:35:39,079 core.sqldb.get_marked_results: Retreving Marked Results for ttmovieid.
INFO 2017-01-01 05:35:39,081 core.sqldb.get_distinct: Getting distinct values for ttmovieid in SEARCHRESULTS
INFO 2017-01-01 05:35:39,083 core.updatestatus.movie_status: Setting MOVIES ttmovieid status to Wanted.
INFO 2017-01-01 05:35:39,084 core.sqldb.update: Updating ttmovieidto Wanted in MOVIES.

If I configure it to talk directly to a third party indexer, it does then show things as found, however I then hit the blank screen issue others have logged.

**Comment by soundjester** [comment]
You'll probably also need to raise this issue with the Docker maintainer. @nosmokingbandit does not directly support the Docker image or issues relating to it.

**Comment by vertigo235** [comment]
My nzbhydra setup works fine, but I noticed something odd since switching to nzbhydra, a day or so later, the status of "finished" will be replaced with what appears to be the IMDB ID, so that causes watcher to snatch the next result and download the movie again. 

This may or may not be related to nzbhydra, but I would say it probably isn't. 

NZBHydra is good at removing all the duplicates if you use multiple indexers, because watcher doesn't seem to do that yet and it will keep downloading the same post over and over.

**Comment by vertigo235** [comment]
Forgot to mention that I'm also using the docker image.

**Comment by WilliamJBrown** [comment]
All good on my end for NZBhydra. How are you using the config for it. http://1.1.1.1:9090/? That's how mine is laid out and it works good. just updated nzbhydra too myself.

**Comment by selotapeb** [comment]
Yeah I think the issue is down to my configuration, so this can be closed. It works fine if I use teh local URL, but if I use the URL through reverse proxy then it's a problem.
