### ISSUE TITLE
Mini settings error

### ISSUE THREAD

**Issue by Safihre** [nosmokingbandit/watcher#92]
If no theme was selected by user, it will always default to the Dark one in the Settings page.
![image](https://cloud.githubusercontent.com/assets/5703454/21603067/bd6b1590-d19a-11e6-8024-3a5bd15270f9.png)

Maybe you find it interesting( or maybe you find me annoying 😃 ), but just wanted to give some things we found with SAB that might be usefull for Watcher:
In SABnzbd I made restarting using CherryPy instant by setting:
```python
cherrypy.config.update({
                            'server.shutdown_timeout': 1 
})
```
Otherwise CherryPy will wait 5 seconds before actually restarting to wait for incoming connections.
There's a bug in CherryPy that doesn't allow you to set it to 0, for which I submitted a PR to them (https://github.com/cherrypy/cherrypy/pull/1528) so for now the lowest you can go is 1.

We also added a filter to our logging to strip out all the CherryPy access logging, since it really clogs up the logs:
https://github.com/sabnzbd/sabnzbd/blob/develop/SABnzbd.py#L133-L148
Filter:
https://github.com/sabnzbd/sabnzbd/blob/develop/SABnzbd.py#L1144

**Comment by WilliamJBrown** [comment]
Just adding that i love the community working together on all the programs we use everyday. I am greatfull for the collaboration that occurs. We love you Dev's <3

**Comment by nosmokingbandit** [comment]
Iirc, the shutdown delay only happens if there were requests within 5 seconds. If there are no requests it shuts down instantly. The delay is annoying, but not enough for me to put any actual effort into it. I'll add that line to the config though, thanks for the pointers.

I can't replicate the theme thing. I've never used the Dark theme but it defaults to Default for me... What browser are you using? I use Dominate for templating and it is a little tricky to set up Selects and Options.

I turned off access logging a few commits ago. I just add this line to the main script:
```

cherrypy.log.error_log.propagate = True
cherrypy.log.access_log.propagate = False
```

This lets errors log, but no access logs. Access still prints to an open terminal, but not to the log file.

I could never figure out why CP logs things like the engine start/stop as an error, but it works so...

**Comment by Safihre** [comment]
Aaah didn't know there were easier ways to reduce cherrypy logging, learned something :) 

I use Chrome. If I delete the Config file and thus start from a clean Config which has the light theme selected, in the Config it shows as the dark theme in the `select`. So if you change any other setting and press Save, it will switch you to Dark theme as a side effect.

**Comment by soundjester** [comment]
See, the program just wants you to have the superior theme 😄

**Comment by nosmokingbandit** [comment]
I didn't know a single thing about CherryPy before I started this project, so I feel very accomplished having taught you something :D

Anyway, this is fixed: https://github.com/nosmokingbandit/watcher/commit/df6e11eb45f7b7bce813f15192c1b4672e508689

Just a bad leftover default value in the base config. I had themes set up about 5 different ways before I settled on my method, so this doesn't surprise me.
